/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jetblue.airline;

import Project.ConnectionProvider;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chandika
 */
public class Ticket_Book extends javax.swing.JFrame {

    /**
     * Creates new form Ticket_Book
     */
    public Ticket_Book() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtpassenger_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtpassengername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtpassportnumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        cmbflightcode1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cmbflightcode = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 90, 135));

        jButton4.setBackground(new java.awt.Color(0, 90, 135));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Flight");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 90, 135));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Passengers");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 90, 135));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Tickets");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 90, 135));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Cancellation");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 0));
        jLabel3.setFont(new java.awt.Font("Gabriola", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("JetBlue Airlines");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Welcome Chandika,");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(jLabel10))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1366, 31);

        jPanel3.setBackground(new java.awt.Color(33, 41, 48));

        jLabel1.setForeground(new java.awt.Color(0, 183, 213));
        jLabel1.setText("Ticket Booking");

        jLabel4.setForeground(new java.awt.Color(0, 183, 213));
        jLabel4.setText("Passenger Id");

        jLabel2.setForeground(new java.awt.Color(0, 183, 213));
        jLabel2.setText("Passenger Name");

        jLabel5.setForeground(new java.awt.Color(0, 183, 213));
        jLabel5.setText("Flight Code");

        jLabel6.setForeground(new java.awt.Color(0, 183, 213));
        jLabel6.setText("Passport Number");

        jLabel7.setForeground(new java.awt.Color(0, 183, 213));
        jLabel7.setText("Amount");

        jLabel8.setForeground(new java.awt.Color(0, 183, 213));
        jLabel8.setText("Nationality");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sri Lankan", "American", "Russian", "Japanese" }));

        jButton2.setBackground(new java.awt.Color(174, 214, 216));
        jButton2.setForeground(new java.awt.Color(1, 125, 171));
        jButton2.setText("Book");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(174, 214, 216));
        jButton1.setForeground(new java.awt.Color(1, 125, 171));
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(174, 214, 216));
        jButton3.setForeground(new java.awt.Color(1, 125, 171));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Passenger Id", "Passenger Name", "Flight Code", "Passport Number", "Amount", "nationality"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton8.setBackground(new java.awt.Color(174, 214, 216));
        jButton8.setForeground(new java.awt.Color(1, 125, 171));
        jButton8.setText("Show Data");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        cmbflightcode1.setBackground(new java.awt.Color(233, 219, 216));
        cmbflightcode1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1             AMERICAN AIRLINES INC.", "5             CONTINENTAL AIRLINES, INC.", "6             DELTA AIR LINES, INC.", "12           NORTHWEST AIRLINES, INC.", "14           AIR CANADA", "16           UNITED AIRLINES, INC.", "20           LUFTHANSA CARGO AG.", "23           FEDEX", "43           HONG KONG DRAGON AIRLINES LIMITED.", "55           ALITALIA-COMPAGNIA AEREA ITALIANA S.P.", "57           AIR FRANCE", "63           AIR CALEDONIE INTERNATIONAL", "74           KLM ROYAL DUTCH AIRLINES", "77           EGYPTAIR", "79           PHILIPPINE AIRLINES, INC.", "81           QANTAS AIRWAYS LTD.", "86           AIR NEW ZEALAND LTD.", "96           IRAN-AIR", "98           AIR INDIA LTD.", "105         FINNAIR O/Y", "117         SCANDINAVIAN AIRLINES SYSTEM(SAS)", "125         BRITISH AIRWAYS P.L.C.", "126         GARUDA INDONESIA", "131         JAPAN AIRLINES CO. LTD", "139         AEROMEXICO", "160         CATHAY PACIFIC AIRWAYS LTD.", "172         CARGOLUX AIRLINES INT’L S.A.", "176         EMIRATES SKY CARGO", "180         KOREAN AIR LINES CO.,LTD.", "603         SRILANKAN AIRLINES LTD.", "618         SINGAPORE AIRLINES LTD.", "774         SHANGHAI AIRLINES CO., LTD.", "999         AIR CHINA LTD." }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(txtpassportnumber, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(txtpassengername)
                            .addComponent(txtpassenger_id)
                            .addComponent(cmbflightcode1, 0, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpassenger_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpassengername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbflightcode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpassportnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(270, 150, 760, 460);

        jLabel9.setForeground(new java.awt.Color(0, 90, 135));
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Personal\\Downloads\\New folder (11)\\2.png")); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 30, 1370, 740);

        cmbflightcode.setBackground(new java.awt.Color(233, 219, 216));
        cmbflightcode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1             AMERICAN AIRLINES INC.", "5             CONTINENTAL AIRLINES, INC.", "6             DELTA AIR LINES, INC.", "12           NORTHWEST AIRLINES, INC.", "14           AIR CANADA", "16           UNITED AIRLINES, INC.", "20           LUFTHANSA CARGO AG.", "23           FEDEX", "43           HONG KONG DRAGON AIRLINES LIMITED.", "55           ALITALIA-COMPAGNIA AEREA ITALIANA S.P.", "57           AIR FRANCE", "63           AIR CALEDONIE INTERNATIONAL", "74           KLM ROYAL DUTCH AIRLINES", "77           EGYPTAIR", "79           PHILIPPINE AIRLINES, INC.", "81           QANTAS AIRWAYS LTD.", "86           AIR NEW ZEALAND LTD.", "96           IRAN-AIR", "98           AIR INDIA LTD.", "105         FINNAIR O/Y", "117         SCANDINAVIAN AIRLINES SYSTEM(SAS)", "125         BRITISH AIRWAYS P.L.C.", "126         GARUDA INDONESIA", "131         JAPAN AIRLINES CO. LTD", "139         AEROMEXICO", "160         CATHAY PACIFIC AIRWAYS LTD.", "172         CARGOLUX AIRLINES INT’L S.A.", "176         EMIRATES SKY CARGO", "180         KOREAN AIR LINES CO.,LTD.", "603         SRILANKAN AIRLINES LTD.", "618         SINGAPORE AIRLINES LTD.", "774         SHANGHAI AIRLINES CO., LTD.", "999         AIR CHINA LTD." }));
        jPanel1.add(cmbflightcode);
        cmbflightcode.setBounds(0, 0, 289, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1226, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
        new menu().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String Passenger_id = txtpassenger_id.getText();
        String Passenger_name = txtpassengername.getText();
        String Flight_code = (String)cmbflightcode.getSelectedItem();
        String Passport_number = txtpassportnumber.getText();
        String Amount = txtamount.getText();
        String Nationality = (String)jComboBox1.getSelectedItem();
        //String data[] = {jTextField5.getText(),jTextField1.getText(),jTextField6.getText(),jTextField2.getText(),jTextField3.getText(),jComboBox1.getSelectedItem().toString()};
        
        if(txtpassengername.getText().equals("") && txtpassportnumber.getText().equals("") && txtamount.getText().equals("") && txtpassenger_id.getText().equals("")/*&& txtflightcode.getText().equals("")*/)
        {
            JOptionPane.showMessageDialog(null,"Please Fill the missing Information!");
        }else{
           
                    try{
                        
                        
                        //End
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("insert into ticketbookingtable values('"+Passenger_id+"','"+Passenger_name+"','"+Flight_code+"','"+Passport_number+"','"+Amount+"','"+Nationality+"')");
            JOptionPane.showMessageDialog(null,"Successfully update");
                txtpassengername.setText("");
                txtpassportnumber.setText("");
                txtamount.setText("");
                txtpassenger_id.setText("");
               // txtflightcode.setText("");
            setVisible(false);
            new Ticket_Book().setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Some Error Found");
            setVisible(false);
            new Ticket_Book().setVisible(true);
        }
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        txtpassengername.setText("");
        txtpassportnumber.setText("");
        txtamount.setText("");
        txtpassenger_id.setText("");
       // txtflightcode.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setVisible(false);
        new Flight().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        setVisible(false);
        new Passenger().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //setVisible(false);
        new Ticket_Book().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        setVisible(false);
        new Ticket_Cansallation().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
        //new aded database show
        
        try{
                        
                        //new added!!
                        //open connection
                        Class.forName("com.mysql.jdbc.Driver");
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/jetblueairline","root","");
                        Statement st = con.createStatement();
                        
                        //mySql Quary
                        String sql = "select * from ticketbookingtable";
                        ResultSet rs = st.executeQuery(sql);
                        
                        while(rs.next())
                        {
                            //data will be added untill finish
                            //String id = String.valueOf(rs.getInt("username");//conversion due to int value
                            String Passengerid = rs.getString("passengerid");//flight_code is column name
                            String Passengername = rs.getString("passengername");
                            String Flightcode = rs.getString("flightcode");
                            String Passportnumber = rs.getString("passportnumber");
                            String amount = rs.getString("amount");
                            String nationality = rs.getString("nationality");
                            
                            

                            //string array for store data into Jtable

                            String tbData[] = {Passengerid,Passengername,Flightcode,Passportnumber,amount,nationality};
                            DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();

                            //add string array data into Jtable
                            tblModel.addRow(tbData);
                        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Some Error Found");
            setVisible(false);
            new Ticket_Book().setVisible(true);
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket_Book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbflightcode;
    private javax.swing.JComboBox cmbflightcode1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtpassenger_id;
    private javax.swing.JTextField txtpassengername;
    private javax.swing.JTextField txtpassportnumber;
    // End of variables declaration//GEN-END:variables
}
